id: AD972AAE3
title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab Lingpa
type: translation
pechas:
- I9D42091E
- I8BC594ED
- I7B6173D8
- I7E34D357
- I41E4DFF5
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:52.964195
  last_modified_at: 2023-01-04 11:45:52.964202
  collections:
  - Drimé Ösal Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I9D42091E/E244: 32E2
  I8BC594ED/ACBF: 32E2
  I7B6173D8/FD43: 32E2
  I7E34D357/470A: 32E2
  I41E4DFF5/DA4B: 32E2
